name: test

on: 
  workflow_call:
    inputs:
      repo:
        description: 'Name of the target repository'
        default: 'default'
        required: true
        type: string

jobs:
  add-dbot:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "The name of the repo is ${{ inputs.repo }}"